# Docker Compose for ChatXpert
# © 2024-2025 ELYES. All rights reserved.
# Done by ELYES

version: '3.8'

services:
  # Main application
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - DEBUG=False
      - APP_NAME=ChatXpert
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALGORITHM=HS256
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/chatxpert
      - MONGODB_URL=mongodb://mongodb:27017/chatxpert
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-3.5-turbo
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - mongodb
      - redis
    restart: unless-stopped
    networks:
      - chatxpert-network

  # PostgreSQL database
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatxpert
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - chatxpert-network

  # MongoDB database
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    networks:
      - chatxpert-network

  # Redis cache
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - chatxpert-network

volumes:
  postgres-data:
  mongodb-data:
  redis-data:

networks:
  chatxpert-network:
    driver: bridge 